### ISSUE TITLE
Susscan violation not reported due to issue in the regex pattern in function parse_cfn_guard_output in class scan.py

### ISSUE THREAD

**Issue by rahulsharesth** [awslabs/sustainability-scanner#16]
I am executing the latest version of susscanner with _ensure_all_buckets_have_lifecycle_configuration_ rule. My CF yaml file is   missing lifecycle configuration, however, it is not reported in the susscanner output logs. 

When I debug the code, i see in the "cfn_guard_output" variable violation text/json is present  but regex pattern is not matching hence, output shown is 
{
    "title": "Sustainability Scanner Report",
    "file": "/Users/Rahul_Sharesth/IdeaProjects/pattern_aws_s3/Templates/S3.yml",
    "version": "1.2.5",
    "sustainability_score": 0,
    "failed_rules": []
}

Instead of 

{
    "title": "Sustainability Scanner Report",
    "file": "/Users/Rahul_S/IdeaProjects/pattern_aws_s3/Templates/S3.yml",
    "version": "1.2.5",
    "sustainability_score": 2,
    "failed_rules": [
        {
            "rule_name": "ensure_all_buckets_have_lifecycle_configuration",
            "severity": "MEDIUM",
            "message": "Amazon S3 Lifecycle policies will either delete data or move data between different storage classes based on data access patterns.",
            "links": [
                "https://docs.aws.amazon.com/wellarchitected/latest/sustainability-pillar/sus_sus_data_a4.html",
                "https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-lifecycle-mgmt.html"
            ],
            "resources": [
                {
                    "name": "/Resources/rBucket/Properties",
                    "line": "788"
                }
            ]
        }
    ]
}

The string value in variable cfn_guard_output contains below string snippet, 

/Users/Rahul_S/IdeaProjects/pattern_aws_s3/Templates/S3.yml Status = FAIL
FAILED rules
s3.guard/ensure_all_buckets_have_lifecycle_configuration    FAIL
---
{
  "name": "/Users/Rahul_S/IdeaProjects/pattern_aws_s3/Templates/S3.yml",
  "metadata": {},
  "status": "FAIL",
  "not_compliant": [
    {

The regex is not matching "/Users/Rahul_S/IdeaProjects/pattern_aws_s3/Templates/S3.yml Status = FAIL" due to (}|^) - the start of a line(^)

**Comment by Maurits-de-Groot** [comment]
Hi @rahulsharesth, could you share a minimal version of your yaml file so that I can reproduce the issue?

**Comment by jyriseiger** [comment]
Hi @rahulsharesth, thank you for you finding! It's indeed because of regexp, but not because of new line symbol, but because of / symbols which are part of the full file name. Old version of CloudFormation Guard (which is used by susscanner) produced just file name without full path, new version of CloudFormation Guard produces full name. 
We'll publish updated version soon, which is compatible with latest CloudFormation Guard.

**Comment by Maurits-de-Groot** [comment]
Solved in version 1.2.7 — thank you for reporting it @rahulsharesth
